Update kas-docker script and image
Besides smaller fixes, this brings rejection of building via root/sudo
by default. That should catch a number of build issues.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

diff --git a/kas-docker b/kas-docker
--- a/kas-docker
+++ b/kas-docker
@@ -37,6 +37,9 @@ usage()
 	printf "%b" "clean\t\t\tClean build artifacts, keep downloads.\n"
 	printf "%b" "\nOptional arguments:\n"
 	printf "%b" "--isar\t\t\tUse kas-isar container to build Isar image.\n"
+	printf "%b" "--with-loop-dev		Pass a loop device to the " \
+		    "container. Only required if\n"
+	printf "%b" "\t\t\tloop-mounting is used by recipes.\n"
 	printf "%b" "--docker-args\t\tAdditional arguments to pass to docker " \
 		    "for running the\n"
 	printf "%b" "\t\t\tbuild.\n"
@@ -44,6 +47,7 @@ usage()
 	printf "%b" "--ssh-dir\t\tDirectory containing SSH configurations.\n"
 	printf "%b" "\t\t\tAvoid \$HOME/.ssh unless you fully trust the " \
 		    "container.\n"
+	printf "%b" "--aws-dir\t\tDirectory containing AWScli configuration.\n"
 	printf "%b" "--no-proxy-from-env\tDo not inherit proxy settings from " \
 		    "environment.\n"
 	exit 1
@@ -51,20 +55,20 @@ usage()
 
 trace()
 {
-	[ -n "${VERBOSE}" ] && echo "+ ""$@"
-	eval "$@"
+	[ -n "${VERBOSE}" ] && echo "+ $*"
+	"$@"
 }
 
 if [ -z "${KAS_IMAGE_VERSION}" ]; then
-	KAS_IMAGE_VERSION="2.0"
+	KAS_IMAGE_VERSION="2.1.1"
 fi
 
 DOCKER_IMAGE=kasproject/kas:${KAS_IMAGE_VERSION}
 
 if [ -n "${KAS_WORK_DIR}" ]; then
-	KAS_WORK_DIR=$(readlink -f ${KAS_WORK_DIR})
+	KAS_WORK_DIR=$(readlink -f "${KAS_WORK_DIR}")
 else
-	KAS_WORK_DIR=$(pwd)
+	KAS_WORK_DIR="$(pwd)"
 fi
 
 # parse kas-docker options
@@ -72,6 +76,10 @@ while [ $# -gt 0 ]; do
 	case "$1" in
 	--isar)
 		DOCKER_IMAGE=kasproject/kas-isar:${KAS_IMAGE_VERSION}
+		ISAR_ARGS="--cap-add=SYS_ADMIN --cap-add=MKNOD --privileged"
+		shift 1
+		;;
+	--with-loop-dev)
 		if ! LOOP_DEV=$(/sbin/losetup -f 2>/dev/null); then
 			if [ $(id -u) -eq 0 ]; then
 				echo "Error: loop device not available!"
@@ -89,8 +97,7 @@ while [ $# -gt 0 ]; do
 				exit 1
 			fi
 		fi
-		ISAR_ARGS="--cap-add=SYS_ADMIN --cap-add=MKNOD --privileged \
-			--device ${LOOP_DEV}"
+		WITH_LOOP_DEV="--device ${LOOP_DEV}"
 		shift 1
 		;;
 	--docker-args)
@@ -100,7 +107,12 @@ while [ $# -gt 0 ]; do
 		;;
 	--ssh-dir)
 		[ $# -gt 2 ] || usage
-		SSH_DIR=$2
+		SSH_DIR="$2"
+		shift 2
+		;;
+	--aws-dir)
+		[ $# -gt 2 ] || usage
+		AWS_DIR="$2"
 		shift 2
 		;;
 	--no-proxy-from-env)
@@ -118,12 +130,12 @@ while [ $# -gt 0 ]; do
 		[ $# -eq 1 ] || usage
 		CLEAN_DIR=build/tmp
 		if [ -n "${ISAR_ARGS}" ]; then
-			trace docker run -v ${KAS_WORK_DIR}:/work:rw \
+			trace docker run -v "${KAS_WORK_DIR}":/work:rw \
 					 --workdir=/work --rm ${ISAR_ARGS} \
 					 ${DOCKER_IMAGE} \
 					 sudo rm -rf ${CLEAN_DIR}
 		else
-			trace rm -rf ${KAS_WORK_DIR}/{CLEAN_DIR}
+			trace rm -rf "${KAS_WORK_DIR}/${CLEAN_DIR}"
 		fi
 		exit 0
 		;;
@@ -148,7 +160,7 @@ while [ $# -gt 0 ]; do
 		exit 0
 		;;
 	--skip|--target|--task|-c|--cmd|--command)
-		KAS_OPTIONS="${KAS_OPTIONS} $1 '$2'"
+		KAS_OPTIONS="${KAS_OPTIONS} $1 $2"
 		shift 2
 		;;
 	-*)
@@ -158,15 +170,15 @@ while [ $# -gt 0 ]; do
 	*)
 		KAS_FILES=
 		for FILE in $(IFS=':'; echo $1); do
-			if ! REAL_FILE=$(realpath -qe $FILE); then
+			if ! REAL_FILE="$(realpath -qe "$FILE")"; then
 				echo "Error: configuration file '${FILE}' not found"
 				exit 1
 			fi
 			if [ -z "${KAS_FILES}" ]; then
-				FIRST_KAS_FILE=${REAL_FILE}
-				KAS_FILES=${REAL_FILE}
+				FIRST_KAS_FILE="${REAL_FILE}"
+				KAS_FILES="${REAL_FILE}"
 			else
-				KAS_FILES=${KAS_FILES}:${REAL_FILE}
+				KAS_FILES="${KAS_FILES}:${REAL_FILE}"
 			fi
 		done
 		shift 1
@@ -176,75 +188,90 @@ done
 
 [ -n "${FIRST_KAS_FILE}" ] || usage
 
-KAS_FILE_DIR=$(dirname ${FIRST_KAS_FILE})
+KAS_FILE_DIR="$(dirname "${FIRST_KAS_FILE}")"
 
-REPO_DIR=$(git -C ${KAS_FILE_DIR} rev-parse --show-toplevel 2>/dev/null) \
-	|| REPO_DIR=$(hg --cwd ${KAS_FILE_DIR} root 2>/dev/null) \
+REPO_DIR=$(git -C "${KAS_FILE_DIR}" rev-parse --show-toplevel 2>/dev/null) \
+	|| REPO_DIR=$(hg --cwd "${KAS_FILE_DIR}" root 2>/dev/null) \
 	|| REPO_DIR=${KAS_FILE_DIR}
 
-KAS_FILES=/repo/$(echo ${KAS_FILES} | sed 's|'${REPO_DIR}'/||g;s|:|:/repo/|g')
+KAS_FILES=/repo/"$(echo "${KAS_FILES}" | sed 's|'"${REPO_DIR}"'/||g;s|:|:/repo/|g')"
 
-trace mkdir -p ${KAS_WORK_DIR}
+trace mkdir -p "${KAS_WORK_DIR}"
 
-DOCKER_ARGS="-v ${REPO_DIR}:/repo:ro \
-	     -v ${KAS_WORK_DIR}:/work:rw --workdir=/work \
-	     -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) --rm"
+if [ $(id -u) -eq 0 ] && [ "${KAS_ALLOW_ROOT}" != "yes" ] ; then
+	echo "Error: Running as root - may break certain recipes."
+	echo "Better give a regular user docker access. Set" \
+	     "KAS_ALLOW_ROOT=yes to override."
+	exit 1
+fi
+
+set --  -v "${REPO_DIR}":/repo:ro \
+	-v "${KAS_WORK_DIR}":/work:rw --workdir=/work \
+	-e USER_ID=$(id -u) -e GROUP_ID=$(id -g) --rm
 
 if [ -n "${SSH_DIR}" ] ; then
 	if [ ! -d "${SSH_DIR}" ]; then
-		echo "Passed SSH_VALUE '${SSH_DIR}' is not a directory"
+		echo "Passed SSH_DIR '${SSH_DIR}' is not a directory"
 		exit 1
 	fi
-	DOCKER_ARGS="${DOCKER_ARGS} -v $(readlink -f ${SSH_DIR}):/etc/skel/.ssh:ro"
+	set -- "$@" -v "$(readlink -f "${SSH_DIR}")":/etc/skel/.ssh:ro
+fi
+
+if [ -n "${AWS_DIR}" ] ; then
+	if [ ! -d "${AWS_DIR}" ]; then
+		echo "Passed AWS_DIR '${AWS_DIR}' is not a directory"
+		exit 1
+	fi
+	set -- "$@" -v "$(readlink -f "${AWS_DIR}")":/etc/skel/.aws:ro \
+		-e AWS_CONFIG_FILE="${AWS_CONFIG_FILE:-/etc/skel/.aws/config}" \
+		-e AWS_SHARED_CREDENTIALS_FILE="${AWS_SHARED_CREDENTIALS_FILE:-/etc/skel/.aws/credentials}"
 fi
 
 if [ -t 1 ]; then
-	DOCKER_ARGS="${DOCKER_ARGS} -t -i"
+	set -- "$@" -t -i
 fi
 
 if [ -n "${DL_DIR}" ]; then
-	trace mkdir -p ${DL_DIR}
-	DOCKER_ARGS="${DOCKER_ARGS} \
-		-v $(readlink -f ${DL_DIR}):/downloads:rw \
-		-e DL_DIR=/downloads"
+	trace mkdir -p "${DL_DIR}"
+	set -- "$@" \
+		-v "$(readlink -f "${DL_DIR}")":/downloads:rw \
+		-e DL_DIR=/downloads
 fi
 
 if [ -n "${SSTATE_DIR}" ]; then
-	trace mkdir -p ${SSTATE_DIR}
-	DOCKER_ARGS="${DOCKER_ARGS} \
-		-v $(readlink -f ${SSTATE_DIR}):/sstate:rw \
-		-e SSTATE_DIR=/sstate"
+	trace mkdir -p "${SSTATE_DIR}"
+	set -- "$@" \
+		-v "$(readlink -f "${SSTATE_DIR}")":/sstate:rw \
+		-e SSTATE_DIR=/sstate
 fi
 
 if [ -n "${KAS_REPO_REF_DIR}" ]; then
-	DOCKER_ARGS="${DOCKER_ARGS} \
-		-v $(readlink -f ${KAS_REPO_REF_DIR}):/repo-ref:ro \
-		-e KAS_REPO_REF_DIR=${KAS_REPO_REF_DIR}"
+	set -- "$@" \
+		-v "$(readlink -f "${KAS_REPO_REF_DIR}")":/repo-ref:ro \
+		-e KAS_REPO_REF_DIR="${KAS_REPO_REF_DIR}"
 fi
-
-set -- ${DOCKER_ARGS}
 
 for var in TERM KAS_DISTRO KAS_MACHINE KAS_TARGET KAS_TASK \
            KAS_PREMIRRORS; do
 	if [ -n "$(eval echo \$${var})" ]; then
-		set -- "$@" -e "${var}='$(eval echo \"\$${var}\")'"
+		set -- "$@" -e "${var}=$(eval echo \"\$${var}\")"
 	fi
 done
 
 # propagate only supported SHELL settings
 case "$SHELL" in
 /bin/sh|/bin/bash|/bin/dash)
-	set -- "$@" -e "SHELL='$(eval echo \"\$SHELL\")'"
+	set -- "$@" -e "SHELL=$SHELL"
 	;;
 esac
 
 if [ -z "${NO_PROXY_FROM_ENV+x}" ]; then
 	for var in http_proxy https_proxy ftp_proxy no_proxy NO_PROXY; do
 		if [ -n "$(eval echo \$${var})" ]; then
-			set -- "$@" -e "${var}='$(eval echo \$${var})'"
+			set -- "$@" -e "${var}=$(eval echo \$${var})"
 		fi
 	done
 fi
 
-trace docker run "$@" ${ISAR_ARGS} ${USER_ARGS} \
+trace docker run "$@" ${ISAR_ARGS} ${WITH_LOOP_DEV} ${USER_ARGS} \
 		 ${DOCKER_IMAGE} ${CMD} ${KAS_OPTIONS} ${KAS_FILES}
